set(output "${CMAKE_CURRENT_BINARY_DIR}/字符画导出.png")
file(REMOVE "${output}")
execute_process(COMMAND "${PROGRAM}" "${INPUT}" --output "${output}"
    RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr)
if(NOT result EQUAL 0 OR NOT stdout STREQUAL "" OR NOT stderr STREQUAL "")
    message(FATAL_ERROR "PNG export failed: ${result}: ${stderr}")
endif()
file(READ "${output}" signature LIMIT 8 HEX)
if(NOT signature STREQUAL "89504e470d0a1a0a")
    message(FATAL_ERROR "Invalid PNG signature")
endif()
file(SHA256 "${output}" before)
execute_process(COMMAND "${PROGRAM}" "${INPUT}" --output "${output}"
    RESULT_VARIABLE result OUTPUT_QUIET ERROR_QUIET)
file(SHA256 "${output}" after)
if(NOT result EQUAL 1 OR NOT before STREQUAL after)
    message(FATAL_ERROR "Existing output must be preserved")
endif()
execute_process(COMMAND "${PROGRAM}" "${INPUT}" --format png
    RESULT_VARIABLE result OUTPUT_QUIET ERROR_QUIET)
if(NOT result EQUAL 2)
    message(FATAL_ERROR "Removed --format must be a usage error")
endif()
file(REMOVE "${output}")

# Case-insensitive inferred encoding.
foreach(name IN ITEMS inferred.PNG)
    set(output "${CMAKE_CURRENT_BINARY_DIR}/${name}")
    file(REMOVE "${output}")
    execute_process(COMMAND "${PROGRAM}" "${INPUT}" --output "${output}"
        RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr)
    if(NOT result EQUAL 0 OR NOT stdout STREQUAL "" OR NOT stderr STREQUAL "")
        message(FATAL_ERROR "Output format resolution failed: ${result}: ${stderr}")
    endif()
    file(READ "${output}" signature LIMIT 8 HEX)
    if(NOT signature STREQUAL "89504e470d0a1a0a")
        message(FATAL_ERROR "Resolved output must contain PNG data")
    endif()
    file(REMOVE "${output}")
endforeach()
set(output "${CMAKE_CURRENT_BINARY_DIR}/conflicting.jpg")
file(REMOVE "${output}")
execute_process(COMMAND "${PROGRAM}" "${INPUT}" --output "${output}"
    RESULT_VARIABLE result OUTPUT_QUIET ERROR_QUIET)
if(NOT result EQUAL 2 OR EXISTS "${output}")
    message(FATAL_ERROR "Conflicting format must fail before creating an output")
endif()

foreach(style IN ITEMS short_space short_equals long_equals)
    set(output "${CMAKE_CURRENT_BINARY_DIR}/alias-${style}.png")
    file(REMOVE "${output}")
    if(style STREQUAL "short_space")
        set(output_args -o "${output}")
    elseif(style STREQUAL "short_equals")
        set(output_args "-o=${output}")
    else()
        set(output_args "--output=${output}")
    endif()
    execute_process(COMMAND "${PROGRAM}" "${INPUT}" ${output_args} --columns=1
        RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr)
    if(NOT result EQUAL 0 OR NOT stdout STREQUAL "" OR NOT stderr STREQUAL "")
        message(FATAL_ERROR "Alias/equal syntax failed: ${result}: ${stderr}")
    endif()
    file(READ "${output}" signature LIMIT 8 HEX)
    if(NOT signature STREQUAL "89504e470d0a1a0a")
        message(FATAL_ERROR "Expected PNG from alias/equal syntax")
    endif()
    file(REMOVE "${output}")
endforeach()
